### PR TITLE
Main activity nav

### PR DESCRIPTION
**Pull request by allychoung**
Set up navigation bar in MainActivity, along with skeleton for routing to different UI screens. Added icons to the /drawable folder. 

Things to note: 
- How are we going to pass in args to screens that are specific to a single user (i.e. the profile page of a specific user)?

### CODE REVIEW

**Comment by Stephanie-Delicia** [comment]
You bring up an important note. Would it be enough to pass a user id to a profile screen, and if this id is not the logged in user, the profile screen composable changes display? So each time we navigate to the profile screen, we somehow update the user id. As of right now, the user profile composable takes a UserProfile data object (not the latest one that Thomas pushed to main)

**Comment by tomgrbz** [comment]
I like Stephanie's point. Also its worth noting that to navigate to another user's profile, this would have to be done either through the following list screen, (or a bab? not sure if we mentioned that though) and each of those screens should have access to the data for a user_id, and then when navigating to that page it either loads all the data it needs from RoomDB (the user profile entity) or makes an API call for it. 

I might be overlooking something but this seems right

**Comment by allychoung** [comment]
image

**Comment by Stephanie-Delicia** [comment]
The new nav files are very readable and everything looks good to me! I am able to run the app on my end.

**Review by Stephanie-Delicia — APPROVED** [review]
Everything looks good to me and I think this a good base for further working on screen navigation when all the screens and their functionality are implemented.

**Pull request merged**
