### PR TITLE
Bab feed screen

### PR DESCRIPTION
**Pull request by Stephanie-Delicia**

### CODE REVIEW

**Comment by tomgrbz** [comment]
Just adding that I am able to run it locally. One thing is that it seems the navbar blocks the last Bab on the feed screen, is there anyway to get around that? like maybe make the feed composable a smaller height?

Steph: I can try that right now! 
Update: I adjusted the height for both the feed and profile screen so that the last bab should be fully viewable. The only thing is that this is specific to the pixel 3a as that is the device I'm using. Hopefully it looks better

**Comment by tomgrbz** [comment]
great!

**Comment by Stephanie-Delicia** [comment]
I call upon the wisdom of my peers: I think the bab api works and that the bab feed view model correctly updates its list of babs. But, when I attempt to have the bab feed composable use the VM's list of babs, it comes out as null. I think the issue comes down to my lack of knowing of how to use coroutines - I think the composable isn't getting the bab list because it gets it before the VM successfully uses the api.

**Comment by tomgrbz** [comment]
Hi Steph, I made some changes will push them up now, seems to be working. You'd want to make a stateflow value for each kind of data you need from the view models.

**Review by allychoung — APPROVED** [review]

**Pull request merged**
